---
dist: trusty
language: node_js
node_js:
  - 6
addons:
  chrome: stable

cache: yarn

before_install:
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install

after_script:
  - greenkeeper-lockfile-upload

script:
  - ember test
  - ember build --environment "production"
